server:
  port: 9527

spring:
  application:
    name: mall-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名称进行路由(默认false)
      routes: #路由
        - id: mall_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
          uri: lb://mall-page
          predicates:  # 断言，路径相匹配的进行路由
            - Path=/mall/**
            - After=2020-06-17T12:53:40.325+08:00[Asia/Shanghai]

        - id: payment_route2
          uri: lb://mall-page
          predicates:
            - Path=/payment/lb/** #断言,路径相匹配的进行路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka/

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
